import org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener;
public class FunctionUse869 {
public void funcUse() {
OneTimeExecutionApplicationContextEventListener onetimeexecutionapplicationcontexteventlistener = new OneTimeExecutionApplicationContextEventListener();
onetimeexecutionapplicationcontexteventlistener.isOriginalEventSource(null);
}
}